name: Pipeline

on:
  push:
    branches: [ main ]
    paths:
    - src/**
  pull_request:
    branches: [ main ]
    paths:
    - src/**

workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Build
      run: dotnet build --configuration Release
    - name: Install EF Tool
      run: |
          dotnet new tool-manifest
          dotnet tool install dotnet-ef
    - name: Build dotnet bundle
      run: dotnet ef migrations bundle --project ./src/ConsoleEntityFrameworkBundle.csproj -o bundle_migrations.exe
    - name: Deploy the Database Changes
      run: ./bundle_migrations.exe